export const keys = {
    RETURN: 'Enter',
    BACKSPACE: 'Backspace',
    ESCAPE: 'Escape',
    DELETE: 'Delete',
    SPACE: 'Space',
    UP: 'ArrowUp',
    DOWN: 'ArrowDown',
    PAGE_UP: 'PageUp',
    PAGE_DOWN: 'PageDown',
    HOME: 'Home',
    END: 'End',
    PITCH_LEFT: 'KeyA',
    PITCH_RIGHT: 'KeyD',
    YAW_UP: 'KeyW',
    YAW_DOWN: 'KeyS',
    ROLL_LEFT: 'KeyQ',
    ROLL_RIGHT: 'KeyE',
};
